[project]
name = "todo-mcp"
version = "0.1.0"
description = "Todo list MCP server with SQLite3 storage"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "mcp[cli]>=1.16.0",
]
