[project]
name = "todo-mcp"
version = "0.1.0"
description = "Todo list MCP server with SQLite3 storage"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-dotenv>=1.0.0",
    "mcp>=1.1.0",
    "fastmcp>=0.1.0",
    "openai>=1.0.0",
    "anthropic>=0.18.0",
]
